### ISSUE TITLE
Test unity animation and physics

### ISSUE THREAD

**Issue by XianWorld** [PangaeaStudio/xxxgame#3]
1. test unity animation and physics.
2. find some simple resources similar with the game style.
3. test Ragdoll.
4. test character control.
5. create test project and log the results with wiki

**Comment by XianWorld** [comment]
@skistua 
I highly recommend to see the examples in the Final IK 0.5 package, and you will find lots of fabulous technics we can use for our game.

**Comment by skistua** [comment]
working on it. :-) @XianWorld

**Comment by XianWorld** [comment]
finished, see wiki - Animation studies.
