### ISSUE TITLE
[Wiki]: Collect resources for technology studies

### ISSUE THREAD

**Issue by XianWorld** [PangaeaStudio/xxxgame#4]
* animation
* physics
* FSM/AI
* framework
* networks

**Comment by XianWorld** [comment]
@skistua 

All resources shared in Baidu cloud as below:

链接：http://pan.baidu.com/s/1bnq8PRp 密码：5wr4

**Comment by XianWorld** [comment]
passwords if needs:
tinyworlds
www.s*****.com(shows in the readme)

**Comment by skistua** [comment]
@XianWorld 
All resources were transferred to baidu cloud of mine. share link could be close by now
